// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsKV2F67H0e17B_fzOkGkYcpD-6CiuqM',
    appId: '1:664305180623:web:13d22477699f41defc3cba',
    messagingSenderId: '664305180623',
    projectId: 'kib-workers',
    authDomain: 'kib-workers.firebaseapp.com',
    storageBucket: 'kib-workers.appspot.com',
    measurementId: 'G-NTWS29595N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GsV7dJtVV85KY80wcHYMZX_-RlrqZv8',
    appId: '1:664305180623:android:0badb4a5fcac75e7fc3cba',
    messagingSenderId: '664305180623',
    projectId: 'kib-workers',
    storageBucket: 'kib-workers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgXchQaGPSpfbyFRJXlmqyAxikU7_6YrE',
    appId: '1:664305180623:ios:88f654510476ba6ffc3cba',
    messagingSenderId: '664305180623',
    projectId: 'kib-workers',
    storageBucket: 'kib-workers.appspot.com',
    androidClientId: '664305180623-gs942bc9cc0tv6cbo0eqjap416gg921u.apps.googleusercontent.com',
    iosClientId: '664305180623-c80kbqs8m3apasj00dulnsopkukg95cs.apps.googleusercontent.com',
    iosBundleId: 'com.kib',
  );
}
