name: kib
description: Kib's main application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  animate_do: ^2.0.0
  pin_code_fields: ^7.3.0
  country_code_picker: ^2.0.2
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_crashlytics: ^2.4.4
  cloud_firestore: ^3.1.5
  firebase_storage: ^10.2.4
  google_sign_in: ^5.1.1
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+4
  webview_flutter: ^3.0.0
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  intl: ^0.17.0
  connectivity_plus: ^2.2.0
  http: ^0.13.4
  cloud_firestore_odm: ^1.0.0-dev.6
  json_annotation: ^4.4.0
  firebase_messaging: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  cloud_firestore_odm_generator: ^1.0.0-dev.6
  json_serializable: ^6.1.4

flutter:
  assets:
    - assets/

  uses-material-design: true