// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXiOrThMhXYfY8zCj7xWba4yqZsCxR34',
    appId: '1:269078003569:android:1381c6d8b85280a07380d0',
    messagingSenderId: '269078003569',
    projectId: 'kib-main',
    storageBucket: 'kib-main.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAojTWsmEbmG3kw2ahI4cv3o-uMXXLaWoY',
    appId: '1:269078003569:ios:956705f52a86233e7380d0',
    messagingSenderId: '269078003569',
    projectId: 'kib-main',
    storageBucket: 'kib-main.appspot.com',
    androidClientId: '269078003569-2g58mme5fh4iitihifnpm5majn99p7mo.apps.googleusercontent.com',
    iosClientId: '269078003569-c2qcmoakvtegbntjj64jgckgp3egtkhv.apps.googleusercontent.com',
    iosBundleId: 'com.kib',
  );
}
